[jwt]
aud = 'rere'
iss = 'shandyCho@test.com'
sub = 'axumpractice@test.com'
secret = 'thisisaxumpracticeapplication'

[axum_config]
addr = '0.0.0.0:3500'

[database]
url = '127.0.0.1:1234'
user = 'test'
password = '1234'